# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# org.gradle.java.home=/lib/jvm/java-17-openjdk/

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=0.1.1-beta+1.20.1
maven_group=com.bug1312
archives_base_name=client_base

# Dependencies
fabric_api_version=0.86.1+1.20.1